# -*- coding: utf-8 -*-
"""
Created on Thu Jun 20 14:10:19 2019

@author: Anthony Melson
"""

runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: main.app